services:
  webrtc-sfu-server:
    container_name: webrtc-sfu-server
    build: .
    restart: always
    tty: true
    ports:
      - "8000:8000"
      - "2000-2100:2000-2100"
    volumes:
      - "/Users/omchauhan/Developer/Projects/webrtc-sfu-server:/usr/code"
      - /usr/code/node_modules
